#PBS -N terra_test
# Request 1 processor
#PBS -l nodes=1:ppn=20
# Request 30 minutes of wall clock time
#PBS -l walltime=36:00:00
#PBS -j oe
#PBS -m bea
#PBS -M yllo2@illinois.edu

module load parallel
module load zlib libjpeg hdf4/4.2.12
module load zlib hdf5
export PARALLEL="--env PATH --env LD_LIBRARY_PATH --env LOADEDMODULES --env _LMFILES_ --env MODULE_VERSION --env MODULESHOME"
parallel --jobs $PBS_NUM_PPN --sshloginfile $PBS_NODEFILE --workdir $PBS_O_WORKDIR < commands.txt

